/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.File;
import javax.swing.DefaultListModel;
import message.Message;

/**
 *
 * @author dilara
 */
public class FrmRoom extends javax.swing.JFrame {

    public DefaultListModel clientMessagesModel;

    /**
     * Creates new form FrmRoom
     */
    public FrmRoom() {
        initComponents();
        clientMessagesModel = new DefaultListModel();
        lst_messages.setModel(clientMessagesModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmFile = new javax.swing.JFrame();
        btn_sendFile = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_messages = new javax.swing.JList<>();
        txt_message = new javax.swing.JTextField();
        lbl_roomName = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();
        btn_file = new javax.swing.JButton();
        txt_thisclient_name = new javax.swing.JLabel();

        frmFile.setMinimumSize(new java.awt.Dimension(500, 400));
        frmFile.setPreferredSize(new java.awt.Dimension(500, 400));

        btn_sendFile.setText("Send File");
        btn_sendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendFileActionPerformed(evt);
            }
        });

        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        javax.swing.GroupLayout frmFileLayout = new javax.swing.GroupLayout(frmFile.getContentPane());
        frmFile.getContentPane().setLayout(frmFileLayout);
        frmFileLayout.setHorizontalGroup(
            frmFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmFileLayout.createSequentialGroup()
                .addGroup(frmFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmFileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmFileLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btn_sendFile)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        frmFileLayout.setVerticalGroup(
            frmFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sendFile)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lst_messages.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_messages);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 49, 199, 192));

        txt_message.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        getContentPane().add(txt_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 248, 199, -1));

        lbl_roomName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_roomName.setText("name");
        getContentPane().add(lbl_roomName, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 19, -1, -1));

        btn_send.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        getContentPane().add(btn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 288, -1, -1));

        btn_file.setText("📎");
        btn_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 288, 60, -1));

        txt_thisclient_name.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_thisclient_name.setText("jLabel1");
        getContentPane().add(txt_thisclient_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 251, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        for (Room r : Room.Rooms) {
            if (r.name.equals(lbl_roomName.getText())) {
                for (cClient c : r.clientsOfRoom) {
                    if (c.name.equals(txt_thisclient_name.getText())) {
                        Message msg = new Message(Message.Message_Type.RMessage);
                        msg.additional = lbl_roomName.getText() + " " + c.name;
                        msg.content = txt_message.getText();
                        c.SendMessage(msg);
                    }
                }
            }
        }
        txt_message.setText("");
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_sendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendFileActionPerformed
        File file = fileChooser.getSelectedFile();
        byte[] bytes = cClient.writeFile(file);
        Message m = new Message(Message.Message_Type.File);
        m.additional = "room " + lbl_roomName.getText() + " " + txt_thisclient_name.getText() + " " + file.getName();
        m.content = bytes;
        for (cClient c : cClient.clients) {
            if (c.name.equals(txt_thisclient_name.getText())) {
                c.SendMessage(m);
            }
        }
        String s = "<html><b>" + txt_thisclient_name.getText() + ":" + file.getName() + "</b></html>";
        clientMessagesModel.addElement(s);
        frmFile.setVisible(false);
    }//GEN-LAST:event_btn_sendFileActionPerformed

    private void btn_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fileActionPerformed
        frmFile.setVisible(true);
    }//GEN-LAST:event_btn_fileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_file;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_sendFile;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JFrame frmFile;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbl_roomName;
    private javax.swing.JList<String> lst_messages;
    private javax.swing.JTextField txt_message;
    public javax.swing.JLabel txt_thisclient_name;
    // End of variables declaration//GEN-END:variables
}
